
//Kokiri_Forest_(15)''
var OOT_Kokiri_Forest_Cow = 'adult, eponas song, ocarina'
var OOT_Kokiri_Forest_Kokiri_Sword_Chest = 'nothing'
var OOT_Kokiri_Shop_Item_1 = 'wallet'
var OOT_Kokiri_Shop_Item_2 = 'wallet'
var OOT_Kokiri_Shop_Item_3 = 'wallet'
var OOT_Kokiri_Shop_Item_4 = 'wallet'
var OOT_Kokiri_Shop_Item_5 = 'wallet'
var OOT_Kokiri_Shop_Item_6 = 'wallet'
var OOT_Kokiri_Shop_Item_7 = 'wallet'
var OOT_Kokiri_Shop_Item_8 = 'wallet'
var OOT_Midos_House_Top_Left = 'nothing'
var OOT_Midos_House_Top_Right = 'nothing'
var OOT_Midos_House_Bottom_Left = 'nothing'
var OOT_Midos_House_Bottom_Right = 'nothing'
var OOT_Kokiri_Forest_Storms_Grotto = 'ocarina, songo of storms'

//Hyrule_Field_(8) = ''
var OOT_Hyrule_Field_Ocarina_of_Time = 'kokiris emerald, gorons ruby, zoras sapphire'
var OOT_Hyrule_Field_Song_of_Time = 'kokiris emerald, gorons ruby, zoras sapphire'
var OOT_Hyrule_Field_Grotto_Scrub_HP = 'stone of agony, explosives, wallet'
var OOT_Hyrule_Field_Grotto_Open = 'nothing'
var OOT_Hyrule_Field_Grotto_Southeast = 'explosives'
var OOT_Hyrule_Field_Grotto_Market = 'explosives'
var OOT_Hyrule_Field_Grotto_Tektite_HP = 'stone of agony, explosives'
var OOT_Hyrule_Field_Cow = 'explosives, ocarina, eponas song, magic, (hammer, fire arrows or dins fire) or (dins fire)'

//Market_(41)''
var OOT_Market_Bazaar_Item_1 = 'child, wallet'
var OOT_Market_Bazaar_Item_2 = 'child, wallet'
var OOT_Market_Bazaar_Item_3 = 'child, wallet'
var OOT_Market_Bazaar_Item_4 = 'child, wallet'
var OOT_Market_Bazaar_Item_5 = 'child, wallet'
var OOT_Market_Bazaar_Item_6 = 'child, wallet'
var OOT_Market_Bazaar_Item_7 = 'child, wallet'
var OOT_Market_Bazaar_Item_8 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_1 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_2 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_3 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_4 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_5 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_6 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_7 = 'child, wallet'
var OOT_Market_Potion_Shop_Item_8 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_1 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_2 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_3 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_4 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_5 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_6 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_7 = 'child, wallet'
var OOT_Market_Bombchu_Shop_Item_8 = 'child, wallet'
var OOT_Market_Pot_House_Big_Poes = 'adult, bottle, eponas song, bow'
var OOT_Market_Dog_Lady_HP = 'child'
var OOT_Bombchu_Bowling_Reward_1 = 'child, explosives, wallet'
var OOT_Bombchu_Bowling_Reward_2 = 'child, explosives, wallet'
var OOT_Shooting_Gallery_Child = 'child, wallet'
var OOT_Treasure_Chest_Game_Buy_Key = 'child, wallet'
var OOT_Treasure_Chest_Game_Room_1_Chest_Left = ''
var OOT_Treasure_Chest_Game_Room_1_Chest_Right = ''
var OOT_Treasure_Chest_Game_Room_2_Chest_Left = ''
var OOT_Treasure_Chest_Game_Room_2_Chest_Right = ''
var OOT_Treasure_Chest_Game_Room_3_Chest_Left = ''
var OOT_Treasure_Chest_Game_Room_3_Chest_Right = ''
var OOT_Treasure_Chest_Game_Room_4_Chest_Left = ''
var OOT_Treasure_Chest_Game_Room_4_Chest_Right = ''
var OOT_Treasure_Chest_Game_Room_5_Chest_Left = ''
var OOT_Treasure_Chest_Game_Room_5_Chest_Right = ''
var OOT_Treasure_Chest_Game_HP = 'child, wallet, magic, lens'

//Lon_Lon_Ranch_(10) = ''
var OOT_Lon_Lon_Ranch_Malon_Song = 'child, ocarina, zeldas letter'
var OOT_Lon_Lon_Ranch_Stables_Cow_Left = 'ocarina, eponas song'
var OOT_Lon_Lon_Ranch_Stables_Cow_Right = 'ocarina, eponas song'
var OOT_Lon_Lon_Ranch_Silo_HP = 'child'
var OOT_Lon_Lon_Ranch_Silo_Cow_Front = 'ocarina, eponas song'
var OOT_Lon_Lon_Ranch_Silo_Cow_Back = 'ocarina, eponas song'
var OOT_Lon_Lon_Ranch_Talon_Bottle = 'child, wallet, zeldas letter'
var OOT_Lon_Lon_Ranch_Grotto_Left_Scrub = 'wallet'
var OOT_Lon_Lon_Ranch_Grotto_Center_Scrub = 'wallet'
var OOT_Lon_Lon_Ranch_Grotto_Right_Scrub = 'wallet'

//Hyrule_Castle_(2) ''
var OOT_Malon_Egg = 'child'
var OOT_Great_Fairy_Dins_Fire = 'child, explosives, ocarina, zeldas lullaby'

//NONE_(2)''
var OOT_Zeldas_Letter = 'child, weird egg'
var OOT_Zeldas_Song = 'child, weird egg'

//Outside_Ganons_Castle_(1) ''
var OOT_Great_Fairy_Defense_Upgrade = 'adult, golden gauntlets, ocarina, zeldas lullaby'

//Lost_Woods_(14)''
var OOT_Lost_Woods_Target = 'child, slingshot'
var OOT_Lost_Woods_Skull_Kid = 'child, ocarina, sarias song'
var OOT_Lost_Woods_Memory_Game = 'child, ocarina'
var OOT_Lost_Woods_Scrub_Sticks_Upgrade = '((slingshot or boomerang or deku shield) + child) or ((hylian shield or bow or hookshot or hammer) + adult) or nuts, wallet' //this needs a collective function
var OOT_Lost_Woods_Odd_Mushroom = 'adult, cojiro'
var OOT_Lost_Woods_Poachers_Saw = 'adult, odd potion'
var OOT_Lost_Woods_Grotto_Generic = 'explosives'
var OOT_Lost_Woods_Gift_from_Saria = 'child'
var OOT_Lost_Woods_Scrub_Near_Theater_Left = 'can damage scrubs'
var OOT_Lost_Woods_Scrub_Near_Theater_Right = 'can damage scrubs'
var OOT_Deku_Theater_Sticks_Upgrade = 'child, skull mask'
var OOT_Deku_Theater_Nuts_Upgrade = 'child, mask of truth'
var OOT_Lost_Woods_Grotto_Scrub_Nuts_Upgrade = 'can damage scrubs'
var OOT_Lost_Woods_Grotto_Scrub_Back = 'can damage scrubs'

//Sacred_Forest_Meadow_(5) = ''
var OOT_Sacred_Meadow_Grotto = 'explosives'
var OOT_Sarias_Song = 'child, zeldas letter'
var OOT_Sacred_Meadow_Sheik_Song = 'adult, (sarias song or minuet),  ocarina'
var OOT_Sacred_Meadow_Storms_Grotto_Front_Scrub = '(adult + (sarias song or minuet)) or (child), ocarina, song of storms)'
var OOT_Sacred_Meadow_Storms_Grotto_Back_Scrub = '(adult + (sarias song or minuet)) or (child), ocarina, song of storms)'

//Kakariko_(34)''
var OOT_Kakariko_Anju_Bottle = 'child'
var OOT_Kakariko_Anju_Egg = 'adult'
var OOT_Kakariko_Anju_Cojiro = 'pocket chicken'
var OOT_Kakariko_Song_Shadow = 'forest medallion, fire medallion, water medallion'
var OOT_Kakariko_Man_on_Roof = 'adult, hookshot'
var OOT_Kakariko_Bazaar_Item_1 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_2 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_3 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_4 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_5 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_6 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_7 = 'adult, wallet'
var OOT_Kakariko_Bazaar_Item_8 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_1 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_2 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_3 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_4 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_5 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_6 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_7 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Item_8 = 'adult, wallet'
var OOT_Kakariko_Potion_Shop_Odd_Potion = 'adult, odd mushroom'
var OOT_Shooting_Gallery_Adult = 'adult, bow, wallet'
var OOT_Kakariko_Cow = 'ocarina, eponas song'
var OOT_Kakariko_Impa_House_HP ='nothing'
var OOT_Windmill_HP = '(adult + ocarina + song of time) or (child + boomerang)'
var OOT_Windmill_Song_of_Storms = 'adult, ocarina'
var OOT_Skulltula_House_10_Tokens = 'token count 10'
var OOT_Skulltula_House_20_Tokens = 'token count 20'
var OOT_Skulltula_House_30_Tokens = 'token count 30'
var OOT_Skulltula_House_40_Tokens = 'token count 40'
var OOT_Skulltula_House_50_Tokens = 'token count 50'
var OOT_Kakariko_Grotto_Front = 'explosives, stone of agony'
var OOT_Kakariko_Grotto_Back = 'nothing'

//Graveyard_(8)''
var OOT_Graveyard_Dampe_Game = 'child, wallet'
var OOT_Graveyard_Crate_HP = '(child, adult, magic beans) or (adult, longshot)'
var OOT_Graveyard_Royal_Tomb_Song = 'ocarina, zeldas lullaby'
var OOT_Graveyard_Royal_Tomb_Chest = 'ocarina, zeldas lullaby, magic, ((child + dins fire) or (adult + (dins fire or (bow + fire arrows)))' //need child fire and adult fire functions
var OOT_Graveyard_Fairy_Tomb = 'nothing'
var OOT_Graveyard_ReDead_Tomb = 'ocarina, suns song'
var OOT_Graveyard_Dampe_Tomb_Reward_1 = 'adult'
var OOT_Graveyard_Dampe_Tomb_Reward_2 = 'adult'

//Death_Mountain_Trail_(8) = ''
var OOT_Death_Mountain_Trail_Chest = 'explosives'
var OOT_Death_Mountain_Trail_HP = 'nothing'
var OOT_Death_Mountain_Trail_Prescription = 'adult, broken goron sword'
var OOT_Death_Mountain_Trail_Claim_Check = 'adult, eyedrops'
var OOT_Death_Mountain_Trail_Biggoron_Sword = 'adult, claim check'
var OOT_Death_Mountain_Trail_Grotto = 'ocarina, song of storms'
var OOT_Death_Mountain_Trail_Cow = 'explosives, ocarina, eponas song'
var OOT_Great_Fairy_Magic_Upgrade = 'explosives, ocarina, zeldas lullaby'

//Goron_City_(19)''
var OOT_Goron_City_Maze_Center_1 = 'explosives or (adult + (hammer or silver gauntlets))'
var OOT_Goron_City_Maze_Center_2 = 'explosives or (adult + (hammer or silver gauntlets))'
var OOT_Goron_City_Maze_Left = 'adult + (hammer or silver gauntlets))'
var OOT_Goron_City_Big_Pot_HP = 'child, sticks, (ocarina + zeldas lullaby) or (magic + dins fire)'
var OOT_Goron_City_Tunic ='adult, explosives or bow or goron bracelet'
var OOT_Goron_City_Bomb_Bag = 'child, explosives'
var OOT_Goron_City_Medigoron_Giant_Knife = 'adult, adult wallet, (explosives or hammer or goron bracelet)'
var OOT_Darunia ='child, ocarina, zeldas lullaby, sarias song)'
var OOT_Goron_Shop_Item_1 = 'wallet'
var OOT_Goron_Shop_Item_2 = 'wallet'
var OOT_Goron_Shop_Item_3 = 'wallet'
var OOT_Goron_Shop_Item_4 = 'wallet'
var OOT_Goron_Shop_Item_5 = 'wallet'
var OOT_Goron_Shop_Item_6 = 'wallet'
var OOT_Goron_Shop_Item_7 = 'wallet'
var OOT_Goron_Shop_Item_8 = 'wallet'
var OOT_Goron_City_Grotto_Left_Scrub = 'can damage scrubs, adult, (hookshot/longshot), (song of time or goron tunic), wallet'
var OOT_Goron_City_Grotto_Center_Scrub = 'can damage scrubs, adult, (hookshot/longshot), (song of time or goron tunic), wallet'
var OOT_Goron_City_Grotto_Right_Scrub = 'can damage scrubs, adult, (hookshot/longshot), (song of time or goron tunic), wallet'

//Zoras_River_(8) = ''
var OOT_Zora_River_Bean_Seller = 'child, (explosives or silver scale)'
var OOT_Zora_River_HP_Pillar = '(child, (explosives or silver scale)) or (adult + hover boots)'
var OOT_Zora_River_HP_Platform = 'child or (adult + hover boots)'
var OOT_Zora_River_Frogs_Storms = 'child, (explosives or silver scale), ocarina, song of storms'
var OOT_Zora_River_Frogs_Game = 'child, (explosives or silver scale), ocarina, zeldas lullaby, eponas song, sarias song, song of time, suns song, song of storms'
var OOT_Zora_River_Storms_Grotto_Front_Scrub = 'can damage scrubs, (child + (explosives or silver scale)) or (adult), ocarina, song of storms, wallet'
var OOT_Zora_River_Storms_Grotto_Back_Scrub = 'can damage scrubs, (child + (explosives or silver scale)) or (adult), ocarina, song of storms, wallet'
var OOT_Zora_River_Grotto = 'adult or (child + (explosives or silver scale))'

//Zoras_Domain_(12) = '(child, (silver scale or (ocarina, zeldas lullaby, explosives))) or (adult, ocarina, zeldas lullaby)' needs seperate functions for adult and child
var OOT_Zora_Domain_Waterfall_Chest ='enter zd child, sticks'
var OOT_Zora_Domain_Diving_Game = 'enter zd child, wallet'
var OOT_Zora_Domain_Tunic = 'enter zd adult, bottle, blue fire' //need to have access to stuff as a check
var OOT_Zora_Domain_Eyeball_Frog = 'enter zd adult, bottle, blue fire, prescription'
var OOT_Zora_Shop_Item_1 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_2 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_3 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_4 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_5 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_6 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_7 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'
var OOT_Zora_Shop_Item_8 = 'enter zd child or (enter zd adult + bottle + blue fire), wallet'

//Lake_Hylia_(10) = ''
var OOT_Lake_Hylia_Underwater_Bottle = 'child,  silver scale'
var OOT_Lake_Hylia_Fire_Arrow = 'adult, bow, (morpha HC location or (scarecrows song + ocarina + longshot))' //locations as checks and scarecrows song
var OOT_Lake_Hylia_HP = '(child + magic beans + adult) or (adult + ocarina + scarecrows song + hookshot)'
var OOT_Laboratory_Dive ='gold scale'
var OOT_Laboratory_Eye_Drops = 'adult, eyeball frog'
var OOT_Fishing_Pond_Child = 'child, wallet'
var OOT_Fishing_Pond_Adult = 'adult, (morpha HC location or (ocarina + scarecrows song + hookshot))'
var OOT_Lake_Hylia_Grotto_Left_Scrub = 'can damage scrubs'
var OOT_Lake_Hylia_Grotto_Center_Scrub = 'can damage scrubs'
var OOT_Lake_Hylia_Grotto_Right_Scrub = 'can damage scrubs'

//Zoras_Fountain_(3) = 'enter zd child, rutos letter'
var OOT_Zora_Fountain_Iceberg_HP = 'enter zf, adult'
var OOT_Zora_Fountain_Bottom_HP = 'enter zf, adult, iron boots, zora tunic'
var OOT_Great_Fairy_Farores_Wind = 'enter zf, explosives, ocarina, zeldas lullaby'

//Temple_of_Time_(3) = ''
var OOT_Temple_of_Time_Master_Sword = '' //heavily depends on setting
var OOT_Temple_of_Time_Sheik_Song = 'adult, forest medallion'
var OOT_Temple_of_Time_Light_Arrows = '' //heavily depends on setting

//Sacred_Realm_(1) = ''
var OOT_Temple_of_Time_Medallion = 'nothing'

//Death_Mountain_Crater_(9) = '' //upper and lower need dif requirements
var OOT_Death_Mountain_Crater_Alcove_HP = ''
var OOT_Death_Mountain_Crater_Scrub_Child = ''
var OOT_Death_Mountain_Crater_Volcano_HP = ''
var OOT_Death_Mountain_Crater_Sheik_Song = ''
var OOT_Death_Mountain_Crater_Grotto = ''
var OOT_Death_Mountain_Crater_Grotto_Left_Scrub = ''
var OOT_Death_Mountain_Crater_Grotto_Center_Scrub = ''
var OOT_Death_Mountain_Crater_Grotto_Right_Scrub = ''
var OOT_Great_Fairy_Magic_Upgrade_2 = ''

//Gerudo_Valley_(7)''
var OOT_Gerudo_Valley_Crate_HP = ''
var OOT_Gerudo_Valley_Waterfall_HP = ''
var OOT_Gerudo_Valley_Cow = ''
var OOT_Gerudo_Valley_Chest = ''
var OOT_Gerudo_Valley_Broken_Goron_Sword = ''
var OOT_Gerudo_Valley_Grotto_Front_Scrub = ''
var OOT_Gerudo_Valley_Grotto_Back_Scrub = ''

//Gerudos_Fortress_(3) = ''
var OOT_Gerudo_Fortress_Archery_Reward_1 = ''
var OOT_Gerudo_Fortress_Archery_Reward_2 = ''
var OOT_Gerudo_Fortress_Chest = ''

//Haunted_Wasteland_(1) = ''
var OOT_Haunted_Wasteland_Chest = ''
 
//Desert_Colossus_(5) = ''
var OOT_Desert_Colossus_HP = ''
var OOT_Desert_Colossus_Song_Spirit = ''
var OOT_Great_Fairy_Nayrus_Love = ''
var OOT_Desert_Colossus_Grotto_Front_Scrub = ''
var OOT_Desert_Colossus_Grotto_Back_Scrub = ''

//Deku_Tree_(8)''
var OOT_Deku_Tree_Boss_Container = ''
var OOT_Deku_Tree_Boss = ''
var OOT_Deku_Tree_Map_Chest = ''
var OOT_Deku_Tree_Compass_Chest = ''
var OOT_Deku_Tree_Compass_Room_Side_Chest = ''
var OOT_Deku_Tree_Slingshot_Chest = ''
var OOT_Deku_Tree_Slingshot_Side_Chest = ''
var OOT_Deku_Tree_Basement_Chest = ''

//Dodongos_Cavern_(12) = ''
var OOT_Dodongo_Cavern_Boss_Chest = ''
var OOT_Dodongo_Cavern_Boss_Container = ''
var OOT_Dodongo_Cavern_Boss = ''
var OOT_Dodongo_Cavern_Map_Chest = ''
var OOT_Dodongo_Cavern_Lobby_Scrub = ''
var OOT_Dodongo_Cavern_Green_Side_Room_Scrub = ''
var OOT_Dodongo_Cavern_Compass_Chest = ''
var OOT_Dodongo_Cavern_Bomb_Bag_Side_Chest = ''
var OOT_Dodongo_Cavern_Bomb_Bag_Side_Room_Left_Scrub = ''
var OOT_Dodongo_Cavern_Bomb_Bag_Side_Room_Right_Scrub = ''
var OOT_Dodongo_Cavern_Bomb_Bag_Chest = ''
var OOT_Dodongo_Cavern_Bridge_Chest = ''

//Jabu_Jabus_Belly_(6) = ''
var OOT_Jabu_Jabu_Boss_Container = ''
var OOT_Jabu_Jabu_Boss = ''
var OOT_Jabu_Jabu_Map_Chest = ''
var OOT_Jabu_Jabu_Compass_Chest = ''
var OOT_Jabu_Jabu_Boomerang_Chest = ''
var OOT_Jabu_Jabu_Scrub = ''

//Forest_Temple_(15)
var OOT_Forest_Temple_Boss = ''
var OOT_Forest_Temple_Boss_Container = ''
var OOT_Forest_Temple_Tree_Small_Key = ''
var OOT_Forest_Temple_Mini_Boss_Key = ''
var OOT_Forest_Temple_Floormaster = ''
var OOT_Forest_Temple_Map = ''
var OOT_Forest_Temple_Garden = ''
var OOT_Forest_Temple_Well =''
var OOT_Forest_Temple_Maze = ''
var OOT_Forest_Temple_Boss_Key = ''
var OOT_Forest_Temple_Poe_Key = ''
var OOT_Forest_Temple_Bow = ''
var OOT_Forest_Temple_Compass = ''
var OOT_Forest_Temple_Checkerboard = ''
var OOT_Forest_Temple_Antichamber = ''

////Fire_Temple_(16) = ''
var OOT_Fire_Temple_Boss_Container = ''
var OOT_Fire_Temple_Boss = ''
var OOT_Fire_Temple_Jail_1_Chest = ''
var OOT_Fire_Temple_Boss_Key_Side_Chest = ''
var OOT_Fire_Temple_Boss_Key_Chest = ''
var OOT_Fire_Temple_Lava_Room_North_Jail_Chest = ''
var OOT_Fire_Temple_Lava_Room_South_Jail_Chest = ''
var OOT_Fire_Temple_Maze_Chest = ''
var OOT_Fire_Temple_Maze_Jail_Chest = ''
var OOT_Fire_Temple_Map = ''
var OOT_Fire_Temple_Above_Maze_Chest = ''
var OOT_Fire_Temple_Below_Maze_Chest = ''
var OOT_Fire_Temple_Scarecrow_Chest = ''
var OOT_Fire_Temple_Compass = ''
var OOT_Fire_Temple_Ring_Jail = ''
var OOT_Fire_Temple_Hammer =''

//Water_Temple_(12)''
var OOT_Water_Temple_Boss_HC = ''
var OOT_Water_Temple_Boss = ''
var OOT_Water_Temple_Bombable_Chest = ''
var OOT_Water_Temple_Map = ''
var OOT_Water_Temple_Shell_Chest = ''
var OOT_Water_Temple_Under_Center = ''
var OOT_Water_Temple_Compass = ''
var OOT_Water_Temple_Dragon_Chest = ''
var OOT_Water_Temple_Corridor_Chest = ''
var OOT_Water_Temple_Boss_Key_Chest = ''
var OOT_Water_Temple_Longshot = ''
var OOT_Water_Temple_River_Chest = ''

//Spirit_Temple_(36)''
var OOT_Spirit_Temple_Boss_HC = ''
var OOT_Spirit_Temple_Boss = ''
var OOT_Spirit_Temple_Child_First_Chest = ''
var OOT_Spirit_Temple_Child_Second_Chest = ''
var OOT_Spirit_Temple_SR_Child_1 = ''
var OOT_Spirit_Temple_SR_Child_2 = ''
var OOT_Spirit_Temple_SR_Child_3 = ''
var OOT_Spirit_Temple_SR_Child_4 = ''
var OOT_Spirit_Temple_SR_Child_5 = ''
var OOT_Spirit_Temple_Child_Climb_1 = ''
var OOT_Spirit_Temple_Child_Climb_2 = ''
var OOT_Spirit_Temple_Sun_Block_Room_Torches = ''
var OOT_Spirit_Temple_SR_Sun_1 = ''
var OOT_Spirit_Temple_SR_Sun_2 = ''
var OOT_Spirit_Temple_SR_Sun_3 = ''
var OOT_Spirit_Temple_SR_Sun_4 = ''
var OOT_Spirit_Temple_SR_Sun_5 = ''
var OOT_Spirit_Temple_Silver_Gauntlets = ''
var OOT_Spirit_Temple_Adult_Lullaby = ''
var OOT_Spirit_Temple_Adult_Silver_Rupees = ''
var OOT_Spirit_Temple_SR_Boulders_1 = ''
var OOT_Spirit_Temple_SR_Boulders_2 = ''
var OOT_Spirit_Temple_SR_Boulders_3 = ''
var OOT_Spirit_Temple_SR_Boulders_4 = ''
var OOT_Spirit_Temple_SR_Boulders_5 = ''
var OOT_Spirit_Temple_Adult_Suns_on_Wall_1 = ''
var OOT_Spirit_Temple_Adult_Suns_on_Wall_2 = ''
var OOT_Spirit_Temple_Statue_Base =''
var OOT_Spirit_Temple_Statue_Hands = ''
var OOT_Spirit_Temple_Statue_Upper_Right = ''
var OOT_Spirit_Temple_Adult_Late_Sun_on_Wall = ''
var OOT_Spirit_Temple_Adult_Invisible_1 =''
var OOT_Spirit_Temple_Adult_Invisible_2 = ''
var OOT_Spirit_Temple_Mirror_Shield = ''
var OOT_Spirit_Temple_Adult_Boss_Key_Chest = ''
var OOT_Spirit_Temple_Adult_Topmost_Sun_on_Wall = ''

//Shadow_Temple_(34)''
var OOT_Shadow_Temple_Boss_HC = ''
var OOT_Shadow_Temple_Boss = ''
var OOT_Shadow_Temple_Map = ''
var OOT_Shadow_Temple_Hover_Boots = ''
var OOT_Shadow_Temple_Compass = ''
var OOT_Shadow_Temple_SR_Scythe_1 = ''
var OOT_Shadow_Temple_SR_Scythe_2 = ''
var OOT_Shadow_Temple_SR_Scythe_3 = ''
var OOT_Shadow_Temple_SR_Scythe_4 = ''
var OOT_Shadow_Temple_SR_Scythe_5 = ''
var OOT_Shadow_Temple_Silver_Rupees = ''
var OOT_Shadow_Temple_Spinning_Blades_Visible = ''
var OOT_Shadow_Temple_Spinning_Blades_Invisible = ''
var OOT_Shadow_Temple_SR_Pit_1 =''
var OOT_Shadow_Temple_SR_Pit_2 = ''
var OOT_Shadow_Temple_SR_Pit_3 = ''
var OOT_Shadow_Temple_SR_Pit_4 = ''
var OOT_Shadow_Temple_SR_Pit_5 = ''
var OOT_Shadow_Temple_Falling_Spikes_Lower = ''
var OOT_Shadow_Temple_Falling_Spikes_Upper_1 = ''
var OOT_Shadow_Temple_Falling_Spikes_Upper_2 = ''
var OOT_Shadow_Temple_SR_Spikes_Back_Left = ''
var OOT_Shadow_Temple_SR_Spikes_Right =''
var OOT_Shadow_Temple_SR_Spikes_Center = ''
var OOT_Shadow_Temple_SR_Spikes_Front_Left = ''
var OOT_Shadow_Temple_SR_Spikes_Midair = ''
var OOT_Shadow_Temple_Invisible_Spike_Room = ''
var OOT_Shadow_Temple_Skull = ''
var OOT_Shadow_Temple_Wind_Room_Hint = ''
var OOT_Shadow_Temple_After_Wind = ''
var OOT_Shadow_Temple_After_Wind_Invisible = ''
var OOT_Shadow_Temple_Boss_Key_Room_1 = ''
var OOT_Shadow_Temple_Boss_Key_Room_2 = ''
var OOT_Shadow_Temple_Invisible_Floormaster = ''

//Bottom_of_the_Well_(19) = ''
var OOT_Bottom_of_the_Well_Coffin = ''
var OOT_Bottom_of_the_Well_Compass = ''
var OOT_Bottom_of_the_Well_Under_Debris = ''
var OOT_Bottom_of_the_Well_Back_West = ''
var OOT_Bottom_of_the_Well_East = ''
var OOT_Bottom_of_the_Well_Front_West = ''
var OOT_Bottom_of_the_Well_Underwater = ''
var OOT_Bottom_of_the_Well_East_Cage = ''
var OOT_Bottom_of_the_Well_Blood_Chest = ''
var OOT_Bottom_of_the_Well_Underwater_2 = ''
var OOT_Bottom_of_the_Well_Map = ''
var OOT_Bottom_of_the_Well_Pits = ''
var OOT_Bottom_of_the_Well_Lens = ''
var OOT_Bottom_of_the_Well_Lens_Side_Chest = ''
var OOT_Bottom_of_the_Well_SR_1 = ''
var OOT_Bottom_of_the_Well_SR_2 = ''
var OOT_Bottom_of_the_Well_SR_3 = ''
var OOT_Bottom_of_the_Well_SR_4 = ''
var OOT_Bottom_of_the_Well_SR_5 = ''

//Ice_Cavern_(15)''
var OOT_Ice_Cavern_SR_Scythe_Left = ''
var OOT_Ice_Cavern_SR_Scythe_Center_Left = ''
var OOT_Ice_Cavern_SR_Scythe_Back = ''
var OOT_Ice_Cavern_SR_Scythe_Center_Right = ''
var OOT_Ice_Cavern_SR_Scythe_Midair = ''
var OOT_Ice_Cavern_Compass = ''
var OOT_Ice_Cavern_HP =''
var OOT_Ice_Cavern_Map = ''
var OOT_Ice_Cavern_SR_Blocks_Back_Left = ''
var OOT_Ice_Cavern_SR_Blocks_Back_Right = ''
var OOT_Ice_Cavern_SR_Blocks_Center = ''
var OOT_Ice_Cavern_SR_Blocks_Alcove = ''
var OOT_Ice_Cavern_SR_Blocks_Front_Left = ''
var OOT_Ice_Cavern_Iron_Boots = ''
var OOT_Ice_Cavern_Sheik_Song = ''

//Thieves_Hideout_(2)''
var OOT_Gerudo_Fortress_Jail_1 = ''
var OOT_Gerudo_Member_Card = ''

//Gerudos_Training_Ground_(37) = ''
var OOT_Gerudo_Training_Grounds_Entrance_1 = ''
var OOT_Gerudo_Training_Grounds_Entrance_2 = ''
var OOT_Gerudo_Training_Grounds_Stalfos =''
var OOT_Gerudo_Training_Grounds_SR_Slope_Front_Right = ''
var OOT_Gerudo_Training_Grounds_SR_Slope_Front_Left = ''
var OOT_Gerudo_Training_Grounds_SR_Slope_Front_Above = ''
var OOT_Gerudo_Training_Grounds_SR_Slope_Center = ''
var OOT_Gerudo_Training_Grounds_SR_Slope_Back = ''
var OOT_Gerudo_Training_Grounds_Near_Block = ''
var OOT_Gerudo_Training_Grounds_Behind_Block_Invisible = ''
var OOT_Gerudo_Training_Grounds_Behind_Block_Visible = ''
var OOT_Gerudo_Training_Grounds_Behind_Block_Enemy_Back = ''
var OOT_Gerudo_Training_Grounds_Behind_Block_Enemy_Front = ''
var OOT_Gerudo_Training_Maze_Upper_Cage = ''
var OOT_Gerudo_Training_Grounds_Lizalfos =''
var OOT_Gerudo_Training_Grounds_SR_Lava_Front_Left = ''
var OOT_Gerudo_Training_Grounds_SR_Lava_Front_Right = ''
var OOT_Gerudo_Training_Grounds_SR_Lava_Back_Left = ''
var OOT_Gerudo_Training_Grounds_SR_Lava_Back_Center = ''
var OOT_Gerudo_Training_Grounds_SR_Lava_Back_Right = ''
var OOT_Gerudo_Training_Freestanding_Key = ''
var OOT_Gerudo_Training_Maze_Side_Chest_1 =''
var OOT_Gerudo_Training_Maze_Side_Chest_2 = ''
var OOT_Gerudo_Training_Water = ''
var OOT_Gerudo_Training_Grounds_SR_Water_1 = ''
var OOT_Gerudo_Training_Grounds_SR_Water_2 = ''
var OOT_Gerudo_Training_Grounds_SR_Water_3 = ''
var OOT_Gerudo_Training_Grounds_SR_Water_4 = ''
var OOT_Gerudo_Training_Grounds_SR_Water_5 = ''
var OOT_Gerudo_Training_Grounds_Hammer_Room_Switch = ''
var OOT_Gerudo_Training_Grounds_Hammer_Room = ''
var OOT_Gerudo_Training_Grounds_Eye_Statue = ''
var OOT_Gerudo_Training_Maze_Upper_Fake_Ceiling = ''
var OOT_Gerudo_Training_Maze_Chest_1 =''
var OOT_Gerudo_Training_Maze_Chest_2 = ''
var OOT_Gerudo_Training_Maze_Chest_3 = ''
var OOT_Gerudo_Training_Maze_Chest_4 = ''

//Ganons_Castle_(40) = ''
var OOT_Ganon_Castle_Leftmost_Scrub = ''
var OOT_Ganon_Castle_Left_Center_Scrub = ''
var OOT_Ganon_Castle_Right_Center_Scrub = ''
var OOT_Ganon_Castle_Rightmost_Scrub = ''
var OOT_Ganon_Castle_Light_Chest_Around_1 = ''
var OOT_Ganon_Castle_Light_Chest_Around_2 = ''
var OOT_Ganon_Castle_Light_Chest_Around_3 = ''
var OOT_Ganon_Castle_Light_Chest_Around_4 = ''
var OOT_Ganon_Castle_Light_Chest_Around_5 = ''
var OOT_Ganon_Castle_Light_Chest_Around_6 = ''
var OOT_Ganon_Castle_Light_Chest_Center = ''
var OOT_Ganon_Castle_Light_Chest_Lullaby = ''
var OOT_Ganon_Castle_SR_Light_Alcove_Right = ''
var OOT_Ganon_Castle_SR_Light_Alcove_Left = ''
var OOT_Ganon_Castle_SR_Light_Center_Top = ''
var OOT_Ganon_Castle_SR_Light_Center_Right = ''
var OOT_Ganon_Castle_SR_Light_Center_Left = ''
var OOT_Ganon_Castle_Forest_Chest = ''
var OOT_Ganon_Castle_SR_Forest_Center_Right = ''
var OOT_Ganon_Castle_SR_Forest_Front = ''
var OOT_Ganon_Castle_SR_Forest_Back_Right = ''
var OOT_Ganon_Castle_SR_Forest_Back_Middle = ''
var OOT_Ganon_Castle_SR_Forest_Center_Left = ''
var OOT_Ganon_Castle_SR_Fire_Back_Right =''
var OOT_Ganon_Castle_SR_Fire_Left = ''
var OOT_Ganon_Castle_SR_Fire_Far_Right = ''
var OOT_Ganon_Castle_SR_Fire_Front_Right = ''
var OOT_Ganon_Castle_SR_Fire_Black_Pillar = ''
var OOT_Ganon_Castle_Water_Chest_1 = ''
var OOT_Ganon_Castle_Water_Chest_2 = ''
var OOT_Ganon_Castle_SR_Spirit_Center_Midair = ''
var OOT_Ganon_Castle_SR_Spirit_Front_Right = ''
var OOT_Ganon_Castle_SR_Spirit_Center_Bottom = ''
var OOT_Ganon_Castle_SR_Spirit_Back_Left = ''
var OOT_Ganon_Castle_SR_Spirit_Back_Right = ''
var OOT_Ganon_Castle_Spirit_Chest_1 = ''
var OOT_Ganon_Castle_Spirit_Chest_2 = ''
var OOT_Ganon_Castle_Shadow_Chest_1 = ''
var OOT_Ganon_Castle_Shadow_Chest_2 = ''
var OOT_Ganon_Castle_Boss_Key = ''

//mm
//Tingle_(6)''
var MM__Tingle_Map_Clock_Town = ''
var MM__Tingle_Map_Woodfall = ''
var MM__Tingle_Map_Snowhead = ''
var MM__Tingle_Map_Ranch = ''
var MM__Tingle_Map_Great_Bay = ''
var MM__Tingle_Map_Ikana = ''

//South_Clock_Town_(7) = ''
var MM__Clock_Town_Owl_Statue = ''
var MM__Initial_Song_of_Healing = ''
var MM__Clock_Town_Platform_HP = ''
var MM__Clock_Town_South_Chest_Lower = ''
var MM__Clock_Town_South_Chest_Upper = ''
var MM__Clock_Town_Business_Scrub = ''
var MM__Clock_Town_Post_Box = ''

//Milk_Road_(3) = ''
var MM__Milk_Road_Owl_Statue = ''
var MM__Gorman_Track_Garo_Mask = ''
var MM__Gorman_Track_Milk_Purchase = ''

//Southern_Swamp_(14) = ''
var MM__Southern_Swamp_Owl_Statue = ''
var MM__Southern_Swamp_HP = ''
var MM__Southern_Swamp_Scrub_Deed = ''
var MM__Southern_Swamp_Scrub_Shop = ''
var MM__Southern_Swamp_Song_of_Soaring = ''
var MM__Southern_Swamp_Grotto = ''
var MM__Tourist_Information_Pictobox = ''
var MM__Tourist_Information_Boat_Archery = ''
var MM__Tourist_Information_Tingle_Picture = ''
var MM__Swamp_Potion_Shop_Kotake = ''
var MM__Woods_of_Mystery_Grotto = ''
var MM__Swamp_Potion_Shop_Item_1 =''
var MM__Swamp_Potion_Shop_Item_2 = ''
var MM__Swamp_Potion_Shop_Item_3 = ''

//Woodfall_(5) = ''
var MM__Woodfall_Owl_Statue = ''
var MM__Woodfall_Near_Owl_Chest = ''
var MM__Woodfall_Entrance_Chest = ''
var MM__Woodfall_HP_Chest = ''
var MM__Woodfall_Great_Fairy = ''

//Mountain_Village_(8) = ''
var MM__Mountain_Village_Owl_Statue = ''
var MM__Mountain_Village_Waterfall_Chest = ''
var MM__Mountain_Village_Don_Gero_Mask = ''
var MM__Mountain_Village_Frog_Choir_HP = ''
var MM__Mountain_Village_Tunnel_Grotto = ''
var MM__Blacksmith_Razor_Blade = ''
var MM__Blacksmith_Gilded_Sword = ''
var MM__Goron_Graveyard_Mask =''

//Snowhead_(2) = ''
var MM__Snowhead_Owl_Statue = ''
var MM__Snowhead_Great_Fairy = ''

//Great_Bay_Coast_(9) = ''
var MM__Great_Bay_Coast_Owl_Statue = ''
var MM__Great_Bay_Coast_Zora_Mask = ''
var MM__Great_Bay_Coast_HP = ''
var MM__Great_Bay_Coast_Fisherman_HP = ''
var MM__Great_Bay_Coast_Fisherman_Grotto = ''
var MM__Great_Bay_Coast_Cow_Front = ''
var MM__Great_Bay_Coast_Cow_Back = ''
var MM__Laboratory_Zora_Song =''
var MM__Laboratory_Fish_HP = ''

//Zora_Cape_(9) = ''
var MM__Zora_Cape_Owl_Statue = ''
var MM__Zora_Cape_Underwater_Chest = ''
var MM__Zora_Cape_Waterfall_HP = ''
var MM__Zora_Cape_Grotto = ''
var MM__Great_Bay_Great_Fairy = ''
var MM__Zora_Cape_Ledge_Chest_1 = ''
var MM__Zora_Cape_Ledge_Chest_2 = ''
var MM__Waterfall_Rapids_Beaver_Race_1 = ''
var MM__Waterfall_Rapids_Beaver_Race_2 = ''

//Ikana_Canyon_(8) = ''
var MM__Ikana_Canyon_Owl_Statue =''
var MM__Ikana_Valley_Scrub_Rupee = ''
var MM__Ikana_Valley_Scrub_HP = ''
var MM__Ikana_Valley_Scrub_Shop = ''
var MM__Ikana_Valley_Grotto = ''
var MM__Ikana_Great_Fairy = ''
var MM__Music_Box_House_Gibdo_Mask = ''
var MM__Ghost_Hut_HP = ''

//Stone_Tower_(4) = ''
var MM__Stone_Tower_Owl_Statue = ''
var MM__Stone_Tower_Inverted_Chest_1 = ''
var MM__Stone_Tower_Inverted_Chest_2 = ''
var MM__Stone_Tower_Inverted_Chest_3 = ''

//Giants_Dream_(1)''
var MM__Oath_to_Order = ''

//North_Clock_Town_(8) = ''
var MM__Clock_Town_Tree_HP = ''
var MM__Clock_Town_Bomber_Notebook = ''
var MM__Clock_Town_Blast_Mask = ''
var MM__Clock_Town_Keaton_HP = ''
var MM__Clock_Town_Great_Fairy = ''
var MM__Clock_Town_Great_Fairy_Alt = ''
var MM__Deku_Playground_Reward_Any_Day = ''
var MM__Deku_Playground_Reward_All_Days = ''

//West_Clock_Town_(19) = ''
var MM__Clock_Town_Bank_Reward_1 =''
var MM__Clock_Town_Bank_Reward_2 = ''
var MM__Clock_Town_Bank_Reward_3 = ''
var MM__Clock_Town_Rosa_Sisters_HP = ''
var MM__Bomb_Shop_Item_1 =''
var MM__Bomb_Shop_Item_2 = ''
var MM__Bomb_Shop_Bomb_Bag = ''
var MM__Bomb_Shop_Bomb_Bag_2 = ''
var MM__Trading_Post_Item_1 = ''
var MM__Trading_Post_Item_2 = ''
var MM__Trading_Post_Item_3 = ''
var MM__Trading_Post_Item_4 = ''
var MM__Trading_Post_Item_5 = ''
var MM__Trading_Post_Item_6 = ''
var MM__Trading_Post_Item_7 = ''
var MM__Trading_Post_Item_8 = ''
var MM__Curiosity_Shop_All_Night_Mask = ''
var MM__Post_Office_HP = ''
var MM__Swordsman_School_HP = ''

//East_Clock_Town_(14) = ''
var MM__Clock_Town_Silver_Rupee_Chest = ''
var MM__Clock_Town_Postman_Hat = ''
var MM__Astral_Observatory_Passage_Chest = ''
var MM__Mayors_Office_Kafeis_Mask = ''
var MM__Mayors_Office_HP = ''
var MM__Milk_Bar_Troupe_Leader_Mask =''
var MM__Milk_Bar_Madame_Aroma_Bottle = ''
var MM__Milk_Bar_Purchase_Milk = ''
var MM__Milk_Bar_Purchase_Chateau = ''
var MM__Town_Archery_Reward_1 =''
var MM__Town_Archery_Reward_2 = ''
var MM__Chest_Game_HP = ''
var MM__Honey_and_Darling_Reward_Any_Day = ''
var MM__Honey_and_Darling_Reward_All_Days = ''

//Laundry_Pool_(5) = ''
var MM__Clock_Town_Guru_Guru_Mask_Bremen = ''
var MM__Clock_Town_Stray_Fairy = ''
var MM__Kafei_Hideout_Pendant_of_Memories = ''
var MM__Kafei_Hideout_Owner_Reward_1 = ''
var MM__Kafei_Hideout_Owner_Reward_2 = ''

//Stock_Pot_Inn_(8)''
var MM__Stock_Pot_Inn_Guest_Room_Chest = ''
var MM__Stock_Pot_Inn_Staff_Room_Chest = ''
var MM__Stock_Pot_Inn_Room_Key = ''
var MM__Stock_Pot_Inn_Letter_to_Kafei = ''
var MM__Stock_Pot_Inn_Couples_Mask = ''
var MM__Stock_Pot_Inn_Grandma_HP_1 = ''
var MM__Stock_Pot_Inn_Grandma_HP_2 = ''
var MM__Stock_Pot_Inn_Toilet_Hand_HP =''

//Termina_Field_(14) = ''
var MM__Astral_Observatory_Moon_Tear = ''
var MM__Termina_Field_Water_Chest = ''
var MM__Termina_Field_Tall_Grass_Chest = ''
var MM__Termina_Field_Tree_Stump_Chest = ''
var MM__Termina_Field_Kamaro_Mask = ''
var MM__Termina_Field_Tall_Grass_Grotto = ''
var MM__Termina_Field_Peahat_Grotto = ''
var MM__Termina_Field_Bio_Baba_Grotto = ''
var MM__Termina_Field_Dodongo_Grotto = ''
var MM__Termina_Field_Pillar_Grotto = ''
var MM__Termina_Field_Scrub = ''
var MM__Termina_Field_Cow_Front =''
var MM__Termina_Field_Cow_Back = ''
var MM__Termina_Field_Gossip_Stones_HP = ''

//Road_to_Southern_Swamp_(4) = ''
var MM__Road_to_Southern_Swamp_HP = ''
var MM__Swamp_Archery_Reward_1 = ''
var MM__Swamp_Archery_Reward_2 = ''
var MM__Road_to_Southern_Swamp_Grotto = ''

//Deku_Palace_(4)''
var MM__Deku_Palace_HP = ''
var MM__Deku_Palace_Sonata_of_Awakening = ''
var MM__Deku_Palace_Grotto_Chest = ''
var MM__Deku_Shrine_Mask_of_Scents = ''

//Twin_Islands_(6)''
var MM__Goron_Elder = ''
var MM__Twin_Islands_Underwater_Chest_1 = ''
var MM__Twin_Islands_Underwater_Chest_2 = ''
var MM__Twin_Islands_Ramp_Grotto_Chest = ''
var MM__Twin_Islands_Frozen_Grotto_Chest = ''
var MM__Goron_Race_Reward = ''

//Goron_Village_(11)''
var MM__Goron_Village_HP = ''
var MM__Goron_Village_Scrub_Deed = ''
var MM__Goron_Village_Scrub_Bomb_Bag = ''
var MM__Goron_Powder_Keg =''
var MM__Lone_Peak_Shrine_Lens_Chest = ''
var MM__Lone_Peak_Shrine_Boulder_Chest = ''
var MM__Lone_Peak_Shrine_Invisible_Chest = ''
var MM__Goron_Baby =''
var MM__Goron_Shop_Item_1 = ''
var MM__Goron_Shop_Item_2 = ''
var MM__Goron_Shop_Item_3 = ''

//Road_to_Snowhead_(2) = ''
var MM__Path_to_Snowhead_HP = ''
var MM__Path_to_Snowhead_Grotto = ''

//Romani_Ranch_(9) = ''
var MM__Romani_Ranch_Epona_Song = ''
var MM__Romani_Ranch_Aliens = ''
var MM__Romani_Ranch_Cremia_Escort = ''
var MM__Cucco_Shack_Bunny_Mask = ''
var MM__Doggy_Racetrack_Chest = ''
var MM__Doggy_Racetrack_HP = ''
var MM__Romani_Ranch_Barn_Cow_Left = ''
var MM__Romani_Ranch_Barn_Cow_Right_Front = ''
var MM__Romani_Ranch_Barn_Cow_Right_Back = ''

//Pinnacle_Rock_(3) = ''
var MM__Pinnacle_Rock_Chest_1 =''
var MM__Pinnacle_Rock_Chest_2 = ''
var MM__Pinnacle_Rock_HP = ''

//Zora_Hall_(8) = ''
var MM__Zora_Hall_Scene_Lights = ''
var MM__Zora_Shop_Item_1 = ''
var MM__Zora_Shop_Item_2 = ''
var MM__Zora_Shop_Item_3 = ''
var MM__Zora_Hall_Evan_HP = ''
var MM__Zora_Hall_Scrub_HP = ''
var MM__Zora_Hall_Scrub_Shop = ''
var MM__Zora_Hall_Scrub_Deed = ''

//Road_to_Ikana_(3) = ''
var MM__Road_to_Ikana_Chest = ''
var MM__Road_to_Ikana_Grotto = ''
var MM__Road_to_Ikana_Stone_Mask = ''

//Ikana_Graveyard_(6) = ''
var MM__Ikana_Graveyard_Captain_Mask = ''
var MM__Ikana_Graveyard_Grotto = ''
var MM__Beneath_The_Graveyard_Chest = ''
var MM__Beneath_The_Graveyard_Song_of_Storms = ''
var MM__Beneath_The_Graveyard_HP = ''
var MM__Beneath_The_Graveyard_Dampe_Chest = ''

//Woodfall_Temple_(22) = ''
var MM__Woodfall_Temple_Entrance_Chest = ''
var MM__Woodfall_Temple_SF_Entrance = ''
var MM__Woodfall_Temple_SF_Main_Pot = ''
var MM__Woodfall_Temple_SF_Main_Deku_Baba = ''
var MM__Woodfall_Temple_Water_Chest = ''
var MM__Woodfall_Temple_SF_Water_Room_Beehive = ''
var MM__Woodfall_Temple_Map = ''
var MM__Woodfall_Temple_SF_Maze_Skulltula = ''
var MM__Woodfall_Temple_SF_Maze_Beehive = ''
var MM__Woodfall_Temple_SF_Maze_Bubble = ''
var MM__Woodfall_Temple_Compass = ''
var MM__Woodfall_Temple_Dark_Chest = ''
var MM__Woodfall_Temple_Center_Chest = ''
var MM__Woodfall_Temple_SF_Main_Bubble = ''
var MM__Woodfall_Temple_Bow = ''
var MM__Woodfall_Temple_Boss_Key_Chest = ''
var MM__Woodfall_Temple_SF_Pre_Boss_Bottom_Right = ''
var MM__Woodfall_Temple_SF_Pre_Boss_Left = ''
var MM__Woodfall_Temple_SF_Pre_Boss_Top_Right = ''
var MM__Woodfall_Temple_SF_Pre_Boss_Pillar = ''
var MM__Woodfall_Temple_Boss_Container = ''
var MM__Woodfall_Temple_Boss = ''

//Snowhead_Temple_(24)''
var MM__Snowhead_Temple_Bridge_Room = ''
var MM__Snowhead_Temple_SF_Bridge_Under_Platform = ''
var MM__Snowhead_Temple_SF_Bridge_Pillar = ''
var MM__Snowhead_Temple_Map = ''
var MM__Snowhead_Temple_SF_Map_Room = ''
var MM__Snowhead_Temple_Map_Alcove = ''
var MM__Snowhead_Temple_Central_Room_Alcove = ''
var MM__Snowhead_Temple_Pillars_Room = ''
var MM__Snowhead_Temple_Central_Room_Bottom = ''
var MM__Snowhead_Temple_Block_Room = ''
var MM__Snowhead_Temple_Block_Room_Ledge = ''
var MM__Snowhead_Temple_Compass = ''
var MM__Snowhead_Temple_Compass_Room_Ledge = ''
var MM__Snowhead_Temple_SF_Compass_Room_Crate = ''
var MM__Snowhead_Temple_Icicle_Room_Alcove = ''
var MM__Snowhead_Temple_Icicle_Room = ''
var MM__Snowhead_Temple_SF_Dual_Switches = ''
var MM__Snowhead_Temple_Fire_Arrow = ''
var MM__Snowhead_Temple_SF_Snow_Room = ''
var MM__Snowhead_Temple_SF_Dinolfos_1 = ''
var MM__Snowhead_Temple_SF_Dinolfos_2 = ''
var MM__Snowhead_Temple_Boss_Key = ''
var MM__Snowhead_Temple_Boss_HC = ''
var MM__Snowhead_Temple_Boss = ''

//Great_Bay_Temple_(22) = ''
var MM__Great_Bay_Temple_Entrance_Chest = ''
var MM__Great_Bay_Temple_SF_Water_Wheel_Platform = ''
var MM__Great_Bay_Temple_SF_Water_Wheel_Skulltula = ''
var MM__Great_Bay_Temple_SF_Central_Room_Barrel = ''
var MM__Great_Bay_Temple_SF_Central_Room_Underwater_Pot = ''
var MM__Great_Bay_Temple_Map =''
var MM__Great_Bay_Temple_SF_Map_Room_Pot = ''
var MM__Great_Bay_Temple_Baba_Chest = ''
var MM__Great_Bay_Temple_Compass = ''
var MM__Great_Bay_Temple_Compass_Room_Underwater = ''
var MM__Great_Bay_Temple_SF_Compass_Room_Pot = ''
var MM__Great_Bay_Temple_Ice_Arrow = ''
var MM__Great_Bay_Temple_Boss_Key = ''
var MM__Great_Bay_Temple_Green_Pipe_1_Chest = ''
var MM__Great_Bay_Temple_Green_Pipe_2_Lower_Chest = ''
var MM__Great_Bay_Temple_Green_Pipe_2_Upper_Chest = ''
var MM__Great_Bay_Temple_Green_Pipe_3_Chest =''
var MM__Great_Bay_Temple_SF_Green_Pipe_3_Barrel = ''
var MM__Great_Bay_Temple_SF_Pre_Boss_Above_Water = ''
var MM__Great_Bay_Temple_SF_Pre_Boss_Underwater = ''
var MM__Great_Bay_Temple_Boss_HC =''
var MM__Great_Bay_Temple_Boss = ''

//Stone_Tower_Temple_(26)''
var MM__Stone_Tower_Temple_Entrance_Chest = ''
var MM__Stone_Tower_Temple_Entrance_Switch_Chest = ''
var MM__Stone_Tower_Temple_Under_West_Garden_Ledge_Chest = ''
var MM__Stone_Tower_Temple_Under_West_Garden_Lava_Chest = ''
var MM__Stone_Tower_Temple_Map =''
var MM__Stone_Tower_Temple_Center_Sun_Block_Chest = ''
var MM__Stone_Tower_Temple_Center_Across_Water_Chest = ''
var MM__Stone_Tower_Temple_Compass =''
var MM__Stone_Tower_Temple_Water_Sun_Switch_Chest = ''
var MM__Stone_Tower_Temple_Mirrors_Room_Center_Chest = ''
var MM__Stone_Tower_Temple_Mirrors_Room_Right_Chest = ''
var MM__Stone_Tower_Temple_Wind_Room_Ledge_Chest = ''
var MM__Stone_Tower_Temple_Wind_Room_Jail_Chest = ''
var MM__Stone_Tower_Temple_Light_Arrow =''
var MM__Stone_Tower_Temple_Before_Water_Bridge_Chest = ''
var MM__Stone_Tower_Temple_Water_Bridge_Chest = ''
var MM__Stone_Tower_Temple_Inverted_Entrance_Chest = ''
var MM__Stone_Tower_Temple_Inverted_East_Lower_Chest = ''
var MM__Stone_Tower_Temple_Inverted_East_Upper_Chest = ''
var MM__Stone_Tower_Temple_Inverted_East_Middle_Chest = ''
var MM__Stone_Tower_Temple_Inverted_Wizzrobe_Chest = ''
var MM__Stone_Tower_Temple_Inverted_Death_Armos_Chest = ''
var MM__Stone_Tower_Temple_Inverted_Boss_Key = ''
var MM__Stone_Tower_Temple_Inverted_Giant_Mask =''
var MM__Stone_Tower_Temple_Inverted_Boss_HC = ''
var MM__Stone_Tower_Temple_Inverted_Boss = ''

//Pirates_Fortress_Exterior_(3) = ''
var MM__Pirate_Fortress_Entrance_Chest_1 = ''
var MM__Pirate_Fortress_Entrance_Chest_2 = ''
var MM__Pirate_Fortress_Entrance_Chest_3 = ''

//Pirates_Fortress_Sewers_(4) = ''
var MM__Pirate_Fortress_Sewers_Chest_1 = ''
var MM__Pirate_Fortress_Sewers_Chest_2 = ''
var MM__Pirate_Fortress_Sewers_Chest_3 = ''
var MM__Pirate_Fortress_Sewers_HP = ''

//Pirates_Fortress_Interior_(5) = ''
var MM__Pirate_Fortress_Interior_Lower_Chest = ''
var MM__Pirate_Fortress_Interior_Upper_Chest = ''
var MM__Pirate_Fortress_Interior_Hookshot = ''
var MM__Pirate_Fortress_Interior_Aquarium = ''
var MM__Pirate_Fortress_Interior_Silver_Rupee_Chest = ''

//Ikana_Castle_(2) = ''
var MM__Ancient_Castle_of_Ikana_HP = ''
var MM__Ancient_Castle_of_Ikana_Song_Emptiness = ''

//Beneath_The_Well_(4)''
var MM__Beneath_The_Well_Keese_Chest = ''
var MM__Beneath_The_Well_Cow = ''
var MM__Beneath_The_Well_Skulltulla_Chest = ''
var MM__Beneath_The_Well_Mirror_Shield = ''

//Secret_Shrine_(5) = ''
var MM__Secret_Shrine_HP_Chest =''
var MM__Secret_Shrine_Dinalfos_Chest = ''
var MM__Secret_Shrine_Wizzrobe_Chest = ''
var MM__Secret_Shrine_Wart_Chest = ''
var MM__Secret_Shrine_Garo_Master_Chest = ''

//Swamp_Spider_House_(1) = ''
var MM__Swamp_Spider_House_Mask_of_Truth = ''

//Ocean_Spider_House_(2) = ''
var MM__Ocean_Spider_House_Wallet = ''
var MM__Ocean_Spider_House_Chest_HP = ''

//Clock_Tower_Roof_(2)''
var MM__Clock_Tower_Roof_Skull_Kid_Ocarina = ''
var MM__Clock_Tower_Roof_Skull_Kid_Song_of_Time = ''

//The_Moon_(7) = ''
var MM__Moon_Fierce_Deity_Mask =''
var MM__Moon_Trial_Deku_HP = ''
var MM__Moon_Trial_Goron_HP = ''
var MM__Moon_Trial_Zora_HP = ''
var MM__Moon_Trial_Link_Garo_Master_Chest = ''
var MM__Moon_Trial_Link_Iron_Knuckle_Chest = ''
var MM__Moon_Trial_Link_HP = ''

